[package]
name = "license-fetcher"
description = "Fetch licenses of dependencies at build time and embed them into your program."
authors = ["Adam McKellar <dev@mckellar.eu>"]
version = "0.7.2"
edition = "2021"
readme = "README.md"
repository = "https://github.com/WyvernIXTL/license-fetcher"
license = "BSL-1.0"
keywords = ["license", "embed", "fetch", "about", "find"]
exclude = [
    "/tests",
    "/benches",
    "/img",
    "/.vscode",
    "/.github",
    "/build.rs",
    "/cSpell.json",
    "/lic-fetcher.code-workspace",
    "/taskfile.yml"
]


[dependencies]
bincode = "2.0.1"
directories = {version = "6.0.0", optional = true}
log = { version = "0.4.22", optional = true }
miniz_oxide = { version = "0.8.0", optional = true, features = ["std"]}
regex = { version = "1.10.6", optional = true }
serde = { version = "1.0.210", features = ["derive"], optional = true }
serde_json = { version = "1.0.128", optional = true }
simplelog = { version = "0.12.2", optional = true }

[dev-dependencies]
criterion = "0.5.1"
pretty_assertions = "1.4.0"

[features]
default = ["compress"]
compress = ["dep:miniz_oxide"]
build = ["dep:serde_json", "dep:serde", "dep:simplelog", "dep:log", "dep:regex", "dep:directories"]
frozen = []

[[bench]]
name = "bench"
harness = false

[package.metadata.docs.rs]
features = ["build"]
rustdoc-args = ["--cfg", "docsrs"]
