[package]
name = "license-fetcher"
description = "Fetch licenses of dependencies at build time and embed them into your program."
authors = ["Adam McKellar <dev@mckellar.eu>"]
version = "0.1.1"
edition = "2021"
readme = "README.md"
repository = "https://github.com/WyvernIXTL/license-fetcher"
license = "BSL-1.0"
keywords = ["license", "embed", "fetch", "about", "find"]


[dependencies]
bincode = "=2.0.0-rc.3"
git2 = { version = "0.19.0", optional = true }
lz4_flex = {version = "0.11.3", optional = true}
octocrab = { version = "0.39.0", optional = true }
serde = { version = "1.0.210", features = ["derive"], optional = true }
serde_json = { version = "1.0.128", optional = true }
tokio = { version = "1.40.0", optional = true, features = ["rt"] }


[dev-dependencies]
pretty_assertions = "1.4.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"


[features]
default = ["compress"]
compress = ["dep:lz4_flex"]
build = ["dep:serde_json", "dep:serde", "dep:git2", "dep:octocrab", "dep:tokio"]
frozen = []
