words = [
    "badgen",
    "bincode",
    "docsrs",
    "dyn",
    "flicense",
    "fnv",
    "kellar",
    "lossy",
    "mckellar",
    "miniz",
    "mrt",
    "serde",
    "taskfile",
    "thiserr",
    "thiserror",
    "vscode",
    "yml",
    "ꞋꞋŏ",
]
