version: "3"

tasks:
  test:setup:
    desc: "Setup for tests and benchmarks."
    aliases:
      - setup
    dir: "./tests/test_crate"
    cmds:
      - cargo fetch --locked

  test:integration:
    desc: "Run integration test."
    aliases:
      - test
    cmds:
      - cargo test -F build

  test:check:
    desc: call cargo check on all applicable features
    aliases: 
      - check
    cmds:
      - cargo check -F build
    
  bench:
    desc: bench with criterion
    cmds:
      - cargo bench -F build

