version: "3"

output:
  group:
    begin: "::group::{{.TASK}}"
    end: "::endgroup::"

tasks:
  # ---------------------------------- Test ---------------------------------- #

  test:integration:
    desc: "Run integration tests."
    env:
      RUST_BACKTRACE: full
    aliases:
      - test
      - t
    deps:
      - task: test:integration:test-crate
      - task: test:integration:build-script

  test:integration:test-crate:
    desc: "Run integration test with test crate and other unit tests."
    deps:
      - task: setup:test-crate
    env:
      RUST_BACKTRACE: full
    cmds:
      - cargo test -F build

  test:integration:build-script:
    desc: "Run integration test with build script."
    env:
      RUST_BACKTRACE: full
    dir: "./tests/test_buildscript"
    cmds:
      - cargo fetch
      - cargo update
      - cargo run


  # ---------------------------------- Check --------------------------------- #

  test:check:
    desc: call cargo check on all applicable features
    aliases:
      - check
      - c
    deps:
      - task: test:check:1
      - task: test:check:2
      - task: test:check:3

  test:check:1:
    cmds:
      - cargo check

  test:check:2:
    cmds:
      - cargo check -F build

  test:check:3:
    cmds:
      - cargo check -F build,serde


  # ---------------------------------- Bench --------------------------------- #

  setup:test-crate:
    desc: "Setup for tests and benchmarks."
    aliases:
      - setup
    dir: "./tests/test_crate"
    cmds:
      - cargo fetch --locked

  bench:
    desc: bench with criterion
    deps:
      - task: setup:test-crate
    cmds:
      - cargo bench -F build


  # ---------------------------------- MISC ---------------------------------- #

  doc:
    desc: build docs
    env:
      RUSTDOCFLAGS: "--cfg docsrs"
    cmds:
      - cargo +nightly doc --all-features --no-deps

  flamegraph:
    desc: generate flame graph
    cmds:
      - sudo cargo flamegraph --test test_generate_licenses -f build --profile flame --image-width 14000

  flamechart:
    desc: generate flame graph
    cmds:
      - sudo cargo flamegraph --test test_generate_licenses -f build --profile flame --image-width 14000 --flamechart -o flamechart.svg

  flame:
    desc: generate flamegraph and chart
    cmds:
      - task: flamegraph
      - task: flamechart
