version: "3"

tasks:
  test:setup:
    desc: "Setup for tests and benchmarks."
    aliases:
      - setup
    dir: "./tests/test_crate"
    cmds:
      - cargo fetch --locked

  test:integration:
    desc: "Run integration test."
    env:
      RUST_BACKTRACE: full
    aliases:
      - test
      - t
    cmds:
      - cargo test -F build
      - task: test:integration:build-script

  test:integration:build-script:
    desc: "Run integration test with build script."
    dir: "./tests/test_buildscript"
    cmds:
      - cargo fetch
      - cargo update
      - cargo run

  test:check:
    desc: call cargo check on all applicable features
    aliases:
      - check
      - c
    cmds:
      - cargo check -F build
      - cargo check

  bench:
    desc: bench with criterion
    cmds:
      - cargo bench -F build

  doc:
    desc: build docs
    env:
      RUSTDOCFLAGS: "--cfg docsrs"
    cmds:
      - cargo +nightly doc --all-features

  flamegraph:
    desc: generate flame graph
    cmds:
      - sudo cargo flamegraph --test test_generate_licenses -f build --profile flame --image-width 14000

  flamechart:
    desc: generate flame graph
    cmds:
      - sudo cargo flamegraph --test test_generate_licenses -f build --profile flame --image-width 14000 --flamechart -o flamechart.svg

  flame:
    desc: generate flamegraph and chart
    cmds:
      - task: flamegraph
      - task: flamechart
