version: "3"

tasks:
  test:setup:
    desc: "Setup for tests and benchmarks."
    aliases:
      - setup
    dir: "./tests/test_crate"
    cmds:
      - cargo fetch --locked

  test:integration:
    desc: "Run integration test."
    aliases:
      - test
      - t
    cmds:
      - cargo test -F build,config_from_path

  test:check:
    desc: call cargo check on all applicable features
    aliases: 
      - check
      - c
    cmds:
      - cargo check -F build,config_from_path
      - cargo check -F build
      - cargo check
    
  bench:
    desc: bench with criterion
    cmds:
      - cargo bench -F build

  doc:
    desc: build docs
    cmds:
      - cargo +nightly doc --all-features
