name: Benchmark PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-benches:
    name: Run Benches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: boa-dev/criterion-compare-action@v3
        with:
          defaultFeatures: false
          features: "build"
