name: Test Main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: arduino/setup-task@v2
      - run: task setup
      - name: Run Tests
        run: task t
