name: Tests

on:
  push:
    branches:
      - main
    paths: 
    - 'src/**'
    - 'Cargo.lock'
    - 'Cargo.toml'
    - 'tests/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2

      - uses: go-task/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests, Checks and Try Build Docs
        run: task --parallel test:check test:integration doc

  clippy_check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v6
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
