name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Setup Integration Test
        run: cargo fetch --frozen
        working-directory: ./tests/test_crate
      - name: Run Unit Tests
        run: cargo test -F build
